source=./bind.conf

################ Monitors ################
monitorrule=name:^DP-1$,width:2560,height:1440,refresh:144,x:1080,y:1440,scale:1,vrr:1,rr:0
monitorrule=name:^DP-2$,width:1920,height:1080,refresh:75,x:3640,y:1440,scale:1,vrr:0,rr:3
monitorrule=name:^DP-3$,width:3840,height:2160,refresh:60,x:1080,y:0,scale:1.5,vrr:0,rr:0
monitorrule=name:^HDMI-A-1$,width:1920,height:1080,refresh:75,x:0,y:1440,scale:1,vrr:0,rr:1

allow_tearing=1

################ Environment ################
env=XCURSOR_THEME,ProjectSekai
env=XCURSOR_SIZE,24
cursor_theme=ProjectSekai
cursor_size=24

################ Autostart ################
exec=~/.config/mango/reload-waybar-swaybg.sh
exec-once=~/.config/mango/idle.sh
exec-once=mako
exec-once=blueman-applet
exec-once=xfce-polkit

exec-once=signal-desktop
exec-once=sleep 3; spotify

################ Window rules ################
windowrule=isfloating:1,width:1100,height:680,appid:foot_floating
windowrule=isterm:1,appid:foot
windowrule=tags:1,monitor:DP-2,isopensilent:1,appid:[Ss]ignal
windowrule=tags:1,monitor:DP-2,isopensilent:1,appid:[Ss]potify

################ Tags ################
tagrule=id:1,layout_name:dwindle
tagrule=id:2,layout_name:dwindle
tagrule=id:3,layout_name:dwindle
tagrule=id:4,layout_name:dwindle
tagrule=id:5,layout_name:dwindle
tagrule=id:6,layout_name:dwindle
tagrule=id:7,layout_name:dwindle
tagrule=id:8,layout_name:dwindle
tagrule=id:9,layout_name:dwindle

tagrule=id:1,no_hide:1

focus_cross_monitor=1

dwindle_smart_split=1
dwindle_preserve_split=1

################ Input ################
xkb_rules_layout=de
mouse_accel_profile=1
mouse_accel_speed=-0.4

drag_tile_to_tile=1
drag_tile_small=0
drag_corner=4
drag_warp_cursor=0

################ Appearance ################
gappih=8
gappiv=8
gappoh=8
gappov=8
borderpx=3
border_radius=6

rootcolor=0x282828ff
bordercolor=0x3c3836ff
focuscolor=0xd4be98ff
dropcolor=0x28282830

blur=0
blur_layer=0
shadows=0
layer_shadows=0

################ Animations ################
animations=1
layer_animations=1
animation_type_open=zoom
animation_type_close=zoom
animation_fade_in=1
animation_fade_out=1
animation_duration_open=200
animation_duration_move=200
animation_duration_close=250
animation_duration_tag=350
animation_curve_open=0.15,0.9,0.1,1.05
animation_curve_move=0.05,0.9,0.1,1.05
