[[language]]
name = "rust"
formatter = { command = "rustfmt", args = ["--edition", "2024"] }
indent = { tab-width = 4, unit = "  " }

[language-server.tailwindcss-ls]
command = "tailwindcss-language-server"
args = ["--stdio"]

[[language]]
name = "javascript"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "javascript"] }
language-servers = ["typescript-language-server"]

[[language]]
name = "typescript"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "typescript"] }
language-servers = ["typescript-language-server"]

[[language]]
name = "tsx"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "typescript"] }
language-servers = ["typescript-language-server", "tailwindcss-ls"]

[[language]]
name = "html"
roots = [".git"]
language-servers = ["vscode-html-language-server", "emmet-lsp"]
formatter = { command = "prettier", args = ["--parser", "html"] }

[[language]]
name = "css"
language-servers = ["vscode-css-language-server", "tailwindcss-ls"]
formatter = { command = "prettier", args = ["--parser", "css"] }
