RIGHT  seek 5 exact
LEFT   seek -5 exact

Alt+y  add video-zoom -.25
Alt+l  add video-zoom .25

Alt+u  add video-pan-y .05
Alt+i  add video-pan-x -.05
Alt+e  add video-pan-y -.05
Alt+n  add video-pan-x .05

Alt+j  set video-pan-x 0; set video-pan-y 0; set video-zoom 0

r      cycle_values video-rotate 90 180 270 0
